<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">
<html>
<head>
<link rel="stylesheet" type="text/css" href="report/style.css"/>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
</head>
<body>
<!-- <div class="container-fluid" style="-250px;"> -->

<?php $slvlhrs = 0 ?>
<?php $ot = 0 ?>
<?php $offset = 0 ?>
<?php $nightdif = 0 ?>
<?php $late = 0 ?>

<?php $totalearnings = 0 ?>
<?php $totalcontri= 0 ?>
<?php $totaldeduc = 0 ?>

<?php $net = 0 ?>

@foreach ($payslip as $data)
<div style="position:absolute;top:-0.30in;left:3.40in;width:5.57in;line-height:0.20in;"><span style="font-style:normal;font-weight:bold;font-size:8pt;font-family:Arial Narrow;color:#101010">ELJIN CORP</span><span style="font-style:normal;font-weight:bold;font-size:14pt;font-family:Arial Narrow;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:-0.15in;left:2.80in;width:5.57in;line-height:0.16in;"><span style="font-style:normal;font-weight:normal;font-size:6pt;font-family:Arial Narrow;color:#101010">Zone 2 Sta. Rosa Road Brgy Maliwalo Tarlac, City</span><span style="font-style:normal;font-weight:normal;font-size:11pt;font-family:Arial Narrow;color:#000000"> </span><br/></SPAN></div>

<div style="position:absolute;top:0.02in;left:0.3in;width:0.90in;line-height:0.13in;"><span style="font-style:normal;font-weight:bold;font-size:6pt;font-family:Arial Narrow;color:#000000">EMPLOYEE NAME:<span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:Arial Narrow;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:0.02in;left:1.15in;width:1.80in;line-height:0.13in;"><span style="font-style:normal;font-weight:normal;font-size:6pt;font-family:Arial Narrow;color:#000000">{{$data->employee_name}}<span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:Arial Narrow;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:0.02in;left:2.58in;width:0.90in;line-height:0.13in;"><span style="font-style:normal;font-weight:bold;font-size:6pt;font-family:Arial Narrow;color:#000000">JOB STATUS:<span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:Arial Narrow;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:0.02in;left:3.20in;width:0.90in;line-height:0.13in;"><span style="font-style:normal;font-weight:normal;font-size:6pt;font-family:Arial Narrow;color:#000000">Regular<span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:Arial Narrow;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:0.02in;left:3.80in;width:0.90in;line-height:0.13in;"><span style="font-style:normal;font-weight:bold;font-size:6pt;font-family:Arial Narrow;color:#000000">PAY RATE:<span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:Arial Narrow;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:0.02in;left:4.30in;width:0.90in;line-height:0.13in;"><span style="font-style:normal;font-weight:normal;font-size:6pt;font-family:Arial Narrow;color:#000000">{{$data->pay_rate}}<span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:Arial Narrow;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:0.02in;left:5.30in;width:0.90in;line-height:0.13in;"><span style="font-style:normal;font-weight:bold;font-size:6pt;font-family:Arial Narrow;color:#000000">NO OF DAYS<span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:Arial Narrow;color:#000000"> </span><br/></SPAN></div>

<div style="position:absolute;top:0.11in;left:0.3in;width:0.90in;line-height:0.13in;"><span style="font-style:normal;font-weight:bold;font-size:6pt;font-family:Arial Narrow;color:#000000">DEPARTMENT:<span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:Arial Narrow;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:0.11in;left:1.15in;width:0.90in;line-height:0.13in;"><span style="font-style:normal;font-weight:normal;font-size:6pt;font-family:Arial Narrow;color:#000000">{{$data->department}}<span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:Arial Narrow;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:0.11in;left:2.58in;width:0.90in;line-height:0.13in;"><span style="font-style:normal;font-weight:bold;font-size:6pt;font-family:Arial Narrow;color:#000000">RANK FILE:<span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:Arial Narrow;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:0.11in;left:3.20in;width:0.90in;line-height:0.13in;"><span style="font-style:normal;font-weight:normal;font-size:6pt;font-family:Arial Narrow;color:#000000">STAFF<span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:Arial Narrow;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:0.11in;left:3.80in;width:0.90in;line-height:0.13in;"><span style="font-style:normal;font-weight:bold;font-size:6pt;font-family:Arial Narrow;color:#000000">POSITION:<span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:Arial Narrow;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:0.11in;left:4.30in;width:0.90in;line-height:0.13in;"><span style="font-style:normal;font-weight:normal;font-size:6pt;font-family:Arial Narrow;color:#000000">{{$data->job_title}}<span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:Arial Narrow;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:0.11in;left:5.30in;width:0.90in;line-height:0.13in;"><span style="font-style:normal;font-weight:bold;font-size:6pt;font-family:Arial Narrow;color:#000000">{{$data->days}}<span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:Arial Narrow;color:#000000"> </span><br/></SPAN></div>

<div style="position:absolute;top:0.33in;left:-0.25in;width:0.90in;line-height:0.13in;"><span style="font-style:normal;font-weight:bold;font-size:6pt;font-family:Arial Narrow;color:#000000">EARNINGS<span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:Arial Narrow;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:0.33in;left:0.31in;width:0.90in;line-height:0.13in;"><span style="font-style:normal;font-weight:bold;font-size:6pt;font-family:Arial Narrow;color:#000000">HOUR(S)<span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:Arial Narrow;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:0.33in;left:0.80in;width:0.90in;line-height:0.13in;"><span style="font-style:normal;font-weight:bold;font-size:6pt;font-family:Arial Narrow;color:#000000">AMOUNT<span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:Arial Narrow;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:0.33in;left:1.60in;width:0.90in;line-height:0.13in;"><span style="font-style:normal;font-weight:bold;font-size:6pt;font-family:Arial Narrow;color:#000000">DEDUCTIONS<span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:Arial Narrow;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:0.33in;left:2.40in;width:0.90in;line-height:0.13in;"><span style="font-style:normal;font-weight:bold;font-size:6pt;font-family:Arial Narrow;color:#000000">AMOUNT<span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:Arial Narrow;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:0.33in;left:3.20in;width:0.90in;line-height:0.13in;"><span style="font-style:normal;font-weight:bold;font-size:6pt;font-family:Arial Narrow;color:#000000">DEDUCTIONS<span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:Arial Narrow;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:0.33in;left:4.00in;width:0.90in;line-height:0.13in;"><span style="font-style:normal;font-weight:bold;font-size:6pt;font-family:Arial Narrow;color:#000000">AMOUNT<span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:Arial Narrow;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:0.33in;left:4.80in;width:0.90in;line-height:0.13in;"><span style="font-style:normal;font-weight:bold;font-size:6pt;font-family:Arial Narrow;color:#000000">CONTRIBUTIONS<span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:Arial Narrow;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:0.33in;left:5.60in;width:0.90in;line-height:0.13in;"><span style="font-style:normal;font-weight:bold;font-size:6pt;font-family:Arial Narrow;color:#000000">AMOUNT<span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:Arial Narrow;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:0.33in;left:6.20in;width:0.90in;line-height:0.13in;"><span style="font-style:normal;font-weight:bold;font-size:6pt;font-family:Arial Narrow;color:#000000">CONTRIBUTIONS<span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:Arial Narrow;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:0.33in;left:7.00in;width:0.90in;line-height:0.13in;"><span style="font-style:normal;font-weight:bold;font-size:6pt;font-family:Arial Narrow;color:#000000">AMOUNT<span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:Arial Narrow;color:#000000"> </span><br/></SPAN></div>

<div style="position:absolute;top:0.53in;left:-0.25in;width:0.90in;line-height:0.13in;"><span style="font-style:normal;font-weight:normal;font-size:6pt;font-family:Arial Narrow;color:#000000">BASIC PAY<span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:Arial Narrow;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:0.53in;left:0.31in;width:0.90in;line-height:0.13in;"><span style="font-style:normal;font-weight:normal;font-size:6pt;font-family:Arial Narrow;color:#000000">-<span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:Arial Narrow;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:0.53in;left:0.80in;width:0.90in;line-height:0.13in;"><span style="font-style:normal;font-weight:normal;font-size:6pt;font-family:Arial Narrow;color:#000000">{{$data->basic_pay}}<span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:Arial Narrow;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:0.53in;left:1.60in;width:0.90in;line-height:0.13in;"><span style="font-style:normal;font-weight:normal;font-size:6pt;font-family:Arial Narrow;color:#000000">ADVANCE<span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:Arial Narrow;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:0.53in;left:2.40in;width:0.90in;line-height:0.13in;"><span style="font-style:normal;font-weight:normal;font-size:6pt;font-family:Arial Narrow;color:#000000">{{$data->advance}}<span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:Arial Narrow;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:0.53in;left:3.20in;width:0.90in;line-height:0.13in;"><span style="font-style:normal;font-weight:normal;font-size:6pt;font-family:Arial Narrow;color:#000000">BOND DEPOSIT<span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:Arial Narrow;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:0.53in;left:4.00in;width:0.90in;line-height:0.13in;"><span style="font-style:normal;font-weight:normal;font-size:6pt;font-family:Arial Narrow;color:#000000">{{$data->bond_deposit}}<span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:Arial Narrow;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:0.53in;left:4.80in;width:0.90in;line-height:0.13in;"><span style="font-style:normal;font-weight:normal;font-size:6pt;font-family:Arial Narrow;color:#000000">SSS LOAN<span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:Arial Narrow;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:0.53in;left:5.60in;width:0.90in;line-height:0.13in;"><span style="font-style:normal;font-weight:normal;font-size:6pt;font-family:Arial Narrow;color:#000000">0<span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:Arial Narrow;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:0.53in;left:6.20in;width:0.90in;line-height:0.13in;"><span style="font-style:normal;font-weight:normal;font-size:6pt;font-family:Arial Narrow;color:#000000">PHILHEALTH<span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:Arial Narrow;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:0.53in;left:7.00in;width:0.90in;line-height:0.13in;"><span style="font-style:normal;font-weight:normal;font-size:6pt;font-family:Arial Narrow;color:#000000">{{$data->philhealth}}<span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:Arial Narrow;color:#000000"> </span><br/></SPAN></div>

<div style="position:absolute;top:0.65in;left:-0.25in;width:0.90in;line-height:0.13in;"><span style="font-style:normal;font-weight:normal;font-size:6pt;font-family:Arial Narrow;color:#000000">OVERTIME<span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:Arial Narrow;color:#000000"> </span><br/></SPAN></div>

<?php if($data->ot_hrs == "")
{?>
<div style="position:absolute;top:0.65in;left:0.31in;width:0.90in;line-height:0.13in;"><span style="font-style:normal;font-weight:normal;font-size:6pt;font-family:Arial Narrow;color:#000000">0<span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:Arial Narrow;color:#000000"> </span><br/></SPAN></div>
<?php }else{ ?>
<div style="position:absolute;top:0.65in;left:0.31in;width:0.90in;line-height:0.13in;"><span style="font-style:normal;font-weight:normal;font-size:6pt;font-family:Arial Narrow;color:#000000">{{$data->ot_hrs}}<span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:Arial Narrow;color:#000000"> </span><br/></SPAN></div>
<?php } ?>

<?php if($data->ot_amount == "")
{?>
<div style="position:absolute;top:0.65in;left:0.80in;width:0.90in;line-height:0.13in;"><span style="font-style:normal;font-weight:normal;font-size:6pt;font-family:Arial Narrow;color:#000000">0<span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:Arial Narrow;color:#000000"> </span><br/></SPAN></div>
<?php }else{ ?>
<div style="position:absolute;top:0.65in;left:0.80in;width:0.90in;line-height:0.13in;"><span style="font-style:normal;font-weight:normal;font-size:6pt;font-family:Arial Narrow;color:#000000">{{$data->ot_amount}}<span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:Arial Narrow;color:#000000"> </span><br/></SPAN></div>
<?php } ?>

<div style="position:absolute;top:0.65in;left:1.60in;width:0.90in;line-height:0.13in;"><span style="font-style:normal;font-weight:normal;font-size:6pt;font-family:Arial Narrow;color:#000000">CHARGE<span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:Arial Narrow;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:0.65in;left:2.40in;width:0.90in;line-height:0.13in;"><span style="font-style:normal;font-weight:normal;font-size:6pt;font-family:Arial Narrow;color:#000000">{{$data->charge}}<span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:Arial Narrow;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:0.65in;left:3.20in;width:0.90in;line-height:0.13in;"><span style="font-style:normal;font-weight:normal;font-size:6pt;font-family:Arial Narrow;color:#000000">MISC<span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:Arial Narrow;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:0.65in;left:4.00in;width:0.90in;line-height:0.13in;"><span style="font-style:normal;font-weight:normal;font-size:6pt;font-family:Arial Narrow;color:#000000">{{$data->misc}}<span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:Arial Narrow;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:0.65in;left:4.80in;width:0.90in;line-height:0.13in;"><span style="font-style:normal;font-weight:normal;font-size:6pt;font-family:Arial Narrow;color:#000000">SSS PREM<span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:Arial Narrow;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:0.65in;left:5.60in;width:0.90in;line-height:0.13in;"><span style="font-style:normal;font-weight:normal;font-size:6pt;font-family:Arial Narrow;color:#000000">{{$data->sss_prem}}<span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:Arial Narrow;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:0.65in;left:6.20in;width:0.90in;line-height:0.13in;"><span style="font-style:normal;font-weight:normal;font-size:6pt;font-family:Arial Narrow;color:#000000">MUTUAL LOAN<span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:Arial Narrow;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:0.65in;left:7.00in;width:0.90in;line-height:0.13in;"><span style="font-style:normal;font-weight:normal;font-size:6pt;font-family:Arial Narrow;color:#000000">0<span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:Arial Narrow;color:#000000"> </span><br/></SPAN></div>

<div style="position:absolute;top:0.78in;left:-0.25in;width:0.90in;line-height:0.13in;"><span style="font-style:normal;font-weight:normal;font-size:6pt;font-family:Arial Narrow;color:#000000">OFFSET<span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:Arial Narrow;color:#000000"> </span><br/></SPAN></div>


<?php if($data->offset_hrs == "")
{?>
<div style="position:absolute;top:0.78in;left:0.31in;width:0.90in;line-height:0.13in;"><span style="font-style:normal;font-weight:normal;font-size:6pt;font-family:Arial Narrow;color:#000000">0<span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:Arial Narrow;color:#000000"> </span><br/></SPAN></div>
<?php }else{ ?>
<div style="position:absolute;top:0.78in;left:0.31in;width:0.90in;line-height:0.13in;"><span style="font-style:normal;font-weight:normal;font-size:6pt;font-family:Arial Narrow;color:#000000">{{$data->offset_hrs}}<span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:Arial Narrow;color:#000000"> </span><br/></SPAN></div>
<?php } ?>

<?php if($data->offset_amount == "")
{?>
<div style="position:absolute;top:0.78in;left:0.80in;width:0.90in;line-height:0.13in;"><span style="font-style:normal;font-weight:normal;font-size:6pt;font-family:Arial Narrow;color:#000000">0<span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:Arial Narrow;color:#000000"> </span><br/></SPAN></div>
<?php }else{ ?>
<div style="position:absolute;top:0.78in;left:0.80in;width:0.90in;line-height:0.13in;"><span style="font-style:normal;font-weight:normal;font-size:6pt;font-family:Arial Narrow;color:#000000">{{$data->offset_amount}}<span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:Arial Narrow;color:#000000"> </span><br/></SPAN></div>
<?php } ?>

<div style="position:absolute;top:0.78in;left:1.60in;width:0.90in;line-height:0.13in;"><span style="font-style:normal;font-weight:normal;font-size:6pt;font-family:Arial Narrow;color:#000000">meal<span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:Arial Narrow;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:0.78in;left:2.40in;width:0.90in;line-height:0.13in;"><span style="font-style:normal;font-weight:normal;font-size:6pt;font-family:Arial Narrow;color:#000000">{{$data->meal}}<span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:Arial Narrow;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:0.78in;left:3.20in;width:0.90in;line-height:0.13in;"><span style="font-style:normal;font-weight:normal;font-size:6pt;font-family:Arial Narrow;color:#000000">MUTUAL CHARGE<span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:Arial Narrow;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:0.78in;left:4.00in;width:0.90in;line-height:0.13in;"><span style="font-style:normal;font-weight:normal;font-size:6pt;font-family:Arial Narrow;color:#000000">{{$data->mutual_charge}}<span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:Arial Narrow;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:0.78in;left:4.80in;width:0.90in;line-height:0.13in;"><span style="font-style:normal;font-weight:normal;font-size:6pt;font-family:Arial Narrow;color:#000000">PAGIBIG LOAN<span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:Arial Narrow;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:0.78in;left:5.60in;width:0.90in;line-height:0.13in;"><span style="font-style:normal;font-weight:normal;font-size:6pt;font-family:Arial Narrow;color:#000000">0<span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:Arial Narrow;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:0.78in;left:6.20in;width:0.90in;line-height:0.13in;"><span style="font-style:normal;font-weight:normal;font-size:6pt;font-family:Arial Narrow;color:#000000">PAGIBIG PREM<span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:Arial Narrow;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:0.78in;left:7.00in;width:0.90in;line-height:0.13in;"><span style="font-style:normal;font-weight:normal;font-size:6pt;font-family:Arial Narrow;color:#000000">{{$data->pag_ibig_prem}}<span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:Arial Narrow;color:#000000"> </span><br/></SPAN></div>

<div style="position:absolute;top:0.91in;left:-0.25in;width:0.90in;line-height:0.13in;"><span style="font-style:normal;font-weight:normal;font-size:6pt;font-family:Arial Narrow;color:#000000">NIGHTDIF<span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:Arial Narrow;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:0.91in;left:0.31in;width:0.90in;line-height:0.13in;"><span style="font-style:normal;font-weight:normal;font-size:6pt;font-family:Arial Narrow;color:#000000">{{$data->nightdif}}<span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:Arial Narrow;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:0.91in;left:0.80in;width:0.90in;line-height:0.13in;"><span style="font-style:normal;font-weight:normal;font-size:6pt;font-family:Arial Narrow;color:#000000">{{$data->nightdif_amount}}<span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:Arial Narrow;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:0.91in;left:1.60in;width:0.90in;line-height:0.13in;"><span style="font-style:normal;font-weight:normal;font-size:6pt;font-family:Arial Narrow;color:#000000">UNIFORM<span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:Arial Narrow;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:0.91in;left:2.40in;width:0.90in;line-height:0.13in;"><span style="font-style:normal;font-weight:normal;font-size:6pt;font-family:Arial Narrow;color:#000000">{{$data->uniform}}<span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:Arial Narrow;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:0.91in;left:3.20in;width:0.90in;line-height:0.13in;"><span style="font-style:normal;font-weight:normal;font-size:6pt;font-family:Arial Narrow;color:#000000">-<span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:Arial Narrow;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:0.91in;left:4.00in;width:0.90in;line-height:0.13in;"><span style="font-style:normal;font-weight:normal;font-size:6pt;font-family:Arial Narrow;color:#000000">-<span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:Arial Narrow;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:0.91in;left:4.80in;width:0.90in;line-height:0.13in;"><span style="font-style:normal;font-weight:normal;font-size:6pt;font-family:Arial Narrow;color:#000000">-<span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:Arial Narrow;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:0.91in;left:5.60in;width:0.90in;line-height:0.13in;"><span style="font-style:normal;font-weight:normal;font-size:6pt;font-family:Arial Narrow;color:#000000">-<span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:Arial Narrow;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:0.91in;left:6.20in;width:0.90in;line-height:0.13in;"><span style="font-style:normal;font-weight:normal;font-size:6pt;font-family:Arial Narrow;color:#000000">-<span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:Arial Narrow;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:0.91in;left:7.00in;width:0.90in;line-height:0.13in;"><span style="font-style:normal;font-weight:normal;font-size:6pt;font-family:Arial Narrow;color:#000000">-<span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:Arial Narrow;color:#000000"> </span><br/></SPAN></div>

<div style="position:absolute;top:1.04in;left:-0.25in;width:0.90in;line-height:0.13in;"><span style="font-style:normal;font-weight:normal;font-size:6pt;font-family:Arial Narrow;color:#000000">OFFDAYS<span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:Arial Narrow;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:1.04in;left:0.31in;width:0.90in;line-height:0.13in;"><span style="font-style:normal;font-weight:normal;font-size:6pt;font-family:Arial Narrow;color:#000000">-<span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:Arial Narrow;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:1.04in;left:0.80in;width:0.90in;line-height:0.13in;"><span style="font-style:normal;font-weight:normal;font-size:6pt;font-family:Arial Narrow;color:#000000">{{$data->offdays_amount}}<span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:Arial Narrow;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:1.04in;left:1.60in;width:0.90in;line-height:0.13in;"><span style="font-style:normal;font-weight:normal;font-size:6pt;font-family:Arial Narrow;color:#000000">-<span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:Arial Narrow;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:1.04in;left:2.40in;width:0.90in;line-height:0.13in;"><span style="font-style:normal;font-weight:normal;font-size:6pt;font-family:Arial Narrow;color:#000000">-<span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:Arial Narrow;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:1.04in;left:3.20in;width:0.90in;line-height:0.13in;"><span style="font-style:normal;font-weight:normal;font-size:6pt;font-family:Arial Narrow;color:#000000">-<span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:Arial Narrow;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:1.04in;left:4.00in;width:0.90in;line-height:0.13in;"><span style="font-style:normal;font-weight:normal;font-size:6pt;font-family:Arial Narrow;color:#000000">-<span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:Arial Narrow;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:1.04in;left:4.80in;width:0.90in;line-height:0.13in;"><span style="font-style:normal;font-weight:normal;font-size:6pt;font-family:Arial Narrow;color:#000000">-<span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:Arial Narrow;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:1.04in;left:5.60in;width:0.90in;line-height:0.13in;"><span style="font-style:normal;font-weight:normal;font-size:6pt;font-family:Arial Narrow;color:#000000">-<span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:Arial Narrow;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:1.04in;left:6.20in;width:0.90in;line-height:0.13in;"><span style="font-style:normal;font-weight:normal;font-size:6pt;font-family:Arial Narrow;color:#000000">-<span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:Arial Narrow;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:1.04in;left:7.00in;width:0.90in;line-height:0.13in;"><span style="font-style:normal;font-weight:normal;font-size:6pt;font-family:Arial Narrow;color:#000000">-<span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:Arial Narrow;color:#000000"> </span><br/></SPAN></div>

<div style="position:absolute;top:1.17in;left:-0.25in;width:0.90in;line-height:0.13in;"><span style="font-style:normal;font-weight:normal;font-size:6pt;font-family:Arial Narrow;color:#000000">HOLIDAY<span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:Arial Narrow;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:1.17in;left:0.31in;width:0.90in;line-height:0.13in;"><span style="font-style:normal;font-weight:normal;font-size:6pt;font-family:Arial Narrow;color:#000000">-<span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:Arial Narrow;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:1.17in;left:0.80in;width:0.90in;line-height:0.13in;"><span style="font-style:normal;font-weight:normal;font-size:6pt;font-family:Arial Narrow;color:#000000">{{$data->holiday_amount}}<span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:Arial Narrow;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:1.17in;left:1.60in;width:0.90in;line-height:0.13in;"><span style="font-style:normal;font-weight:normal;font-size:6pt;font-family:Arial Narrow;color:#000000">-<span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:Arial Narrow;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:1.17in;left:2.40in;width:0.90in;line-height:0.13in;"><span style="font-style:normal;font-weight:normal;font-size:6pt;font-family:Arial Narrow;color:#000000">-<span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:Arial Narrow;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:1.17in;left:3.20in;width:0.90in;line-height:0.13in;"><span style="font-style:normal;font-weight:normal;font-size:6pt;font-family:Arial Narrow;color:#000000">-<span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:Arial Narrow;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:1.17in;left:4.00in;width:0.90in;line-height:0.13in;"><span style="font-style:normal;font-weight:normal;font-size:6pt;font-family:Arial Narrow;color:#000000">-<span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:Arial Narrow;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:1.17in;left:4.80in;width:0.90in;line-height:0.13in;"><span style="font-style:normal;font-weight:normal;font-size:6pt;font-family:Arial Narrow;color:#000000">-<span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:Arial Narrow;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:1.17in;left:5.60in;width:0.90in;line-height:0.13in;"><span style="font-style:normal;font-weight:normal;font-size:6pt;font-family:Arial Narrow;color:#000000">-<span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:Arial Narrow;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:1.17in;left:6.20in;width:0.90in;line-height:0.13in;"><span style="font-style:normal;font-weight:normal;font-size:6pt;font-family:Arial Narrow;color:#000000">-<span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:Arial Narrow;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:1.17in;left:7.00in;width:0.90in;line-height:0.13in;"><span style="font-style:normal;font-weight:normal;font-size:6pt;font-family:Arial Narrow;color:#000000">-<span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:Arial Narrow;color:#000000"> </span><br/></SPAN></div>

<div style="position:absolute;top:1.30in;left:-0.25in;width:0.90in;line-height:0.13in;"><span style="font-style:normal;font-weight:normal;font-size:6pt;font-family:Arial Narrow;color:#000000">SLVL<span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:Arial Narrow;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:1.30in;left:0.31in;width:0.90in;line-height:0.13in;"><span style="font-style:normal;font-weight:normal;font-size:6pt;font-family:Arial Narrow;color:#000000">-<span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:Arial Narrow;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:1.30in;left:0.80in;width:0.90in;line-height:0.13in;"><span style="font-style:normal;font-weight:normal;font-size:6pt;font-family:Arial Narrow;color:#000000">{{$data->slvl_amount}}<span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:Arial Narrow;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:1.30in;left:1.60in;width:0.90in;line-height:0.13in;"><span style="font-style:normal;font-weight:normal;font-size:6pt;font-family:Arial Narrow;color:#000000">-<span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:Arial Narrow;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:1.30in;left:2.40in;width:0.90in;line-height:0.13in;"><span style="font-style:normal;font-weight:normal;font-size:6pt;font-family:Arial Narrow;color:#000000">-<span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:Arial Narrow;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:1.30in;left:3.20in;width:0.90in;line-height:0.13in;"><span style="font-style:normal;font-weight:normal;font-size:6pt;font-family:Arial Narrow;color:#000000">-<span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:Arial Narrow;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:1.30in;left:4.00in;width:0.90in;line-height:0.13in;"><span style="font-style:normal;font-weight:normal;font-size:6pt;font-family:Arial Narrow;color:#000000">-<span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:Arial Narrow;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:1.30in;left:4.80in;width:0.90in;line-height:0.13in;"><span style="font-style:normal;font-weight:normal;font-size:6pt;font-family:Arial Narrow;color:#000000">-<span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:Arial Narrow;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:1.30in;left:5.60in;width:0.90in;line-height:0.13in;"><span style="font-style:normal;font-weight:normal;font-size:6pt;font-family:Arial Narrow;color:#000000">-<span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:Arial Narrow;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:1.30in;left:6.20in;width:0.90in;line-height:0.13in;"><span style="font-style:normal;font-weight:normal;font-size:6pt;font-family:Arial Narrow;color:#000000">-<span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:Arial Narrow;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:1.30in;left:7.00in;width:0.90in;line-height:0.13in;"><span style="font-style:normal;font-weight:normal;font-size:6pt;font-family:Arial Narrow;color:#000000">-<span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:Arial Narrow;color:#000000"> </span><br/></SPAN></div>


<div style="position:absolute;top:1.43in;left:-0.25in;width:0.90in;line-height:0.13in;"><span style="font-style:normal;font-weight:normal;font-size:6pt;font-family:Arial Narrow;color:#000000">LATE<span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:Arial Narrow;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:1.43in;left:0.31in;width:0.90in;line-height:0.13in;"><span style="font-style:normal;font-weight:normal;font-size:6pt;font-family:Arial Narrow;color:#000000">{{$data->minutes_late}}<span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:Arial Narrow;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:1.43in;left:0.80in;width:0.90in;line-height:0.13in;"><span style="font-style:normal;font-weight:normal;font-size:6pt;font-family:Arial Narrow;color:#000000">{{$data->late_amount}}<span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:Arial Narrow;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:1.43in;left:1.60in;width:0.90in;line-height:0.13in;"><span style="font-style:normal;font-weight:normal;font-size:6pt;font-family:Arial Narrow;color:#000000">-<span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:Arial Narrow;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:1.43in;left:2.40in;width:0.90in;line-height:0.13in;"><span style="font-style:normal;font-weight:normal;font-size:6pt;font-family:Arial Narrow;color:#000000">-<span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:Arial Narrow;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:1.43in;left:3.20in;width:0.90in;line-height:0.13in;"><span style="font-style:normal;font-weight:normal;font-size:6pt;font-family:Arial Narrow;color:#000000">-<span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:Arial Narrow;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:1.43in;left:4.00in;width:0.90in;line-height:0.13in;"><span style="font-style:normal;font-weight:normal;font-size:6pt;font-family:Arial Narrow;color:#000000">-<span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:Arial Narrow;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:1.43in;left:4.80in;width:0.90in;line-height:0.13in;"><span style="font-style:normal;font-weight:normal;font-size:6pt;font-family:Arial Narrow;color:#000000">-<span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:Arial Narrow;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:1.43in;left:5.60in;width:0.90in;line-height:0.13in;"><span style="font-style:normal;font-weight:normal;font-size:6pt;font-family:Arial Narrow;color:#000000">-<span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:Arial Narrow;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:1.43in;left:6.20in;width:0.90in;line-height:0.13in;"><span style="font-style:normal;font-weight:normal;font-size:6pt;font-family:Arial Narrow;color:#000000">-<span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:Arial Narrow;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:1.43in;left:7.00in;width:0.90in;line-height:0.13in;"><span style="font-style:normal;font-weight:normal;font-size:6pt;font-family:Arial Narrow;color:#000000">-<span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:Arial Narrow;color:#000000"> </span><br/></SPAN></div>

<div style="position:absolute;top:1.56in;left:-0.25in;width:0.90in;line-height:0.13in;"><span style="font-style:normal;font-weight:normal;font-size:6pt;font-family:Arial Narrow;color:#000000">UDT/HDY<span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:Arial Narrow;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:1.56in;left:0.31in;width:0.90in;line-height:0.13in;"><span style="font-style:normal;font-weight:normal;font-size:6pt;font-family:Arial Narrow;color:#000000">{{$data->udt_hrs}}<span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:Arial Narrow;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:1.56in;left:0.80in;width:0.90in;line-height:0.13in;"><span style="font-style:normal;font-weight:normal;font-size:6pt;font-family:Arial Narrow;color:#000000">{{$data->udt_amount}}<span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:Arial Narrow;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:1.56in;left:1.60in;width:0.90in;line-height:0.13in;"><span style="font-style:normal;font-weight:normal;font-size:6pt;font-family:Arial Narrow;color:#000000">-<span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:Arial Narrow;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:1.56in;left:2.40in;width:0.90in;line-height:0.13in;"><span style="font-style:normal;font-weight:normal;font-size:6pt;font-family:Arial Narrow;color:#000000">-<span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:Arial Narrow;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:1.56in;left:3.20in;width:0.90in;line-height:0.13in;"><span style="font-style:normal;font-weight:normal;font-size:6pt;font-family:Arial Narrow;color:#000000">-<span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:Arial Narrow;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:1.56in;left:4.00in;width:0.90in;line-height:0.13in;"><span style="font-style:normal;font-weight:normal;font-size:6pt;font-family:Arial Narrow;color:#000000">-<span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:Arial Narrow;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:1.56in;left:4.80in;width:0.90in;line-height:0.13in;"><span style="font-style:normal;font-weight:normal;font-size:6pt;font-family:Arial Narrow;color:#000000">-<span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:Arial Narrow;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:1.56in;left:5.60in;width:0.90in;line-height:0.13in;"><span style="font-style:normal;font-weight:normal;font-size:6pt;font-family:Arial Narrow;color:#000000">-<span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:Arial Narrow;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:1.56in;left:6.20in;width:0.90in;line-height:0.13in;"><span style="font-style:normal;font-weight:normal;font-size:6pt;font-family:Arial Narrow;color:#000000">-<span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:Arial Narrow;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:1.56in;left:7.00in;width:0.90in;line-height:0.13in;"><span style="font-style:normal;font-weight:normal;font-size:6pt;font-family:Arial Narrow;color:#000000">-<span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:Arial Narrow;color:#000000"> </span><br/></SPAN></div>


<?php $totalcontri = $data->sss_loan + $data->sss_prem + $data->pag_ibig_loan + $data->pag_ibig_prem + $data->philhealth?>
<?php $totaldeduc = $data->advance + $data->charge + $data->uniform + $data->bond_deposit + $data->meal + $data->misc + $data->mutual_charge ?>
<?php $totalearnings = ($data->basic_pay + $data->ot_amount + $data->offset_amount + $data->holiday_amount + $data->nightdif_amount + $data->offdays_amount) - ($data->late_amount - $data->udt_amount)?>
<?php $net = $totalearnings - ($totalcontri + $totaldeduc) ?>
<div style="position:absolute;top:1.74in;left:-0.25in;width:0.90in;line-height:0.13in;"><span style="font-style:normal;font-weight:normal;font-size:6pt;font-family:Arial Narrow;color:#000000">GROSS EARNINGS : <span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:Arial Narrow;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:1.74in;left:0.55in;width:0.90in;line-height:0.13in;"><span style="font-style:normal;font-weight:normal;font-size:6pt;font-family:Arial Narrow;color:#000000"><?php echo $totalearnings ?><span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:Arial Narrow;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:1.74in;left:1.10in;width:0.90in;line-height:0.13in;"><span style="font-style:normal;font-weight:normal;font-size:6pt;font-family:Arial Narrow;color:#000000">RETRO : <span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:Arial Narrow;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:1.74in;left:1.45in;width:0.90in;line-height:0.13in;"><span style="font-style:normal;font-weight:normal;font-size:6pt;font-family:Arial Narrow;color:#000000">0<span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:Arial Narrow;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:1.74in;left:2.00in;width:0.90in;line-height:0.13in;"><span style="font-style:normal;font-weight:normal;font-size:6pt;font-family:Arial Narrow;color:#000000">TOTAL DEDUCTIONS : <span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:Arial Narrow;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:1.74in;left:2.90in;width:0.90in;line-height:0.13in;"><span style="font-style:normal;font-weight:normal;font-size:6pt;font-family:Arial Narrow;color:#000000"><?php echo $totaldeduc ?><span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:Arial Narrow;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:1.74in;left:3.60in;width:1.90in;line-height:0.13in;"><span style="font-style:normal;font-weight:normal;font-size:6pt;font-family:Arial Narrow;color:#000000">TOTAL CONTRIBUTIONS : <span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:Arial Narrow;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:1.74in;left:4.65in;width:0.90in;line-height:0.13in;"><span style="font-style:normal;font-weight:normal;font-size:6pt;font-family:Arial Narrow;color:#000000"><?php echo $totalcontri ?><span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:Arial Narrow;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:1.74in;left:6.20in;width:1.90in;line-height:0.13in;"><span style="font-style:normal;font-weight:normal;font-size:6pt;font-family:Arial Narrow;color:#000000">NET PAY : <span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:Arial Narrow;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:1.74in;left:6.63in;width:0.90in;line-height:0.13in;"><span style="font-style:normal;font-weight:normal;font-size:6pt;font-family:Arial Narrow;color:#000000"><?php echo $net ?><span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:Arial Narrow;color:#000000"> </span><br/></SPAN></div>

<div style="position:absolute;top:0.25in;left:-0.32in;width:7.95in;line-height:0.13in;"><span style="font-style:normal;font-weight:bold;font-size:6pt;font-family:Arial Narrow;color:#000000"><hr><span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:Arial Narrow;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:0.45in;left:-0.32in;width:7.95in;line-height:0.13in;"><span style="font-style:normal;font-weight:bold;font-size:6pt;font-family:Arial Narrow;color:#000000"><hr><span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:Arial Narrow;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:1.66in;left:-0.32in;width:7.95in;line-height:0.13in;"><span style="font-style:normal;font-weight:bold;font-size:6pt;font-family:Arial Narrow;color:#000000"><hr><span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:Arial Narrow;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:1.86in;left:-0.32in;width:7.95in;line-height:0.13in;"><span style="font-style:normal;font-weight:bold;font-size:6pt;font-family:Arial Narrow;color:#000000"><hr><span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:Arial Narrow;color:#000000"> </span><br/></SPAN></div>

<div style="position:absolute;top:2.12in;left:6.30in;width:0.90in;line-height:0.13in;"><span style="font-style:normal;font-weight:normal;font-size:6pt;font-family:Arial Narrow;color:#000000">SIGNATURE<span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:Arial Narrow;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:2.06in;left:5.63in;width:1.80in;line-height:0.13in;"><span style="font-style:normal;font-weight:bold;font-size:6pt;font-family:Arial Narrow;color:#000000"><hr><span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:Arial Narrow;color:#000000"> </span><br/></SPAN></div>

@endforeach


<script type="text/javascript">

$(document).ready(function () {
    window.print();
});

</script>


<!-- </div> -->
</body>
</html>